apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-fast-api-deployment
  labels:
    app: k8s-fast-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-fast-api
  template:
    metadata:
      labels:
        app: k8s-fast-api
    spec:
      containers:
      - name: k8s-fast-api
        image: nandini1510/flask-api:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            memory: 400Mi
        env:
          - name: ENV
            valueFrom: 
              configMapKeyRef:
                name: k8s-fast-api-configmap
                key: ENV